version: '3'

services:
  app:
    container_name: part6_app
    build: ../part5/.


  server:
    image: nginx
    container_name: part6_server
    ports:
      - "80:8080"
    build: ../part6/.
    depends_on:
      - app
    